#pragma config(Sensor, in1,    lineTracker,    sensorLineFollower)
#pragma config(Sensor, dgtl1,  bumperSwitch,   sensorTouch)
#pragma config(Sensor, dgtl2,  limitSwitch,    sensorTouch)
#pragma config(Motor,  port1,           backLeft,      tmotorVex393_HBridge, openLoop, reversed, driveLeft)
#pragma config(Motor,  port10,          backRight,     tmotorVex393_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1==1)
	{
		if(SensorValue(limitSwitch)==1)
		{
			if(SensorValue(lineTracker)>50)
			{
				startMotor(backLeft, 63);
				startMotor(backRight, 63);
			}
		}
		else
		{
			waitUntil(SensorValue(limitSwitch)==1)
	}
}
}
