#pragma config(Sensor, dgtl1,  bumperSwitch,   sensorTouch)
#pragma config(Motor,  port1,           backRight,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          backLeft,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1==1)
		{
		stopMotor(backLeft);
		stopMotor(backRight);
	untilBump(bumperSwitch);
		startMotor(backLeft, 30);
		startMotor(backRight, 23);
	wait(11);
		stopMotor(backLeft);
		stopMotor(backRight);
		}

}
