#pragma config(Sensor, dgtl1,  bumperSwitch,   sensorTouch)
#pragma config(Motor,  port1,           backRight,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port10,          backLeft,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1==1)
		{
		stopMotor(backLeft);
		stopMotor(backRight);
	untilBump(bumperSwitch);
		startMotor(backLeft, 26);
		startMotor(backRight, 39.61904761904762);
	wait(9);
		stopMotor(backLeft);
		stopMotor(backRight);
		}

}
